floodrelief/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view()),
    path('api/1/rest-auth/', include('rest_auth.urls')),
    path('api/1/', include('mainapp.api_urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

mainapp/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from . import api_views
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('ngo-volunteer/', views.NgoVolunteerView.as_view(), name='ngovolunteerview'),
    path('medical-info/', views.MedicalView.as_view(), name='medicalview'),
    path('nhm-dpm/', views.NhmDpmView.as_view(), name='nhmdpm'),
    path('map-view/', views.MapView.as_view(), name='mapview'),
    path('request/', views.CreateRequest.as_view(), name='requestview'),
    path('request_update/', api_views.request_update_list, name='api_request_update'),
    # path('volunteer/', views.Maintenance.as_view(), name='registerview'),
    path('volunteer/', views.RegisterVolunteer.as_view(), name='registerview'),
    path('volunteerdata/', views.volunteerdata, name='volunteerdata'),
    path('NGO/', views.RegisterNGO.as_view(), name='ngoregisterview'),
    path('ngoview/', views.ngo_list, name='ngoview'),
    path('NGO/download/', views.download_ngo_list, name='ngo_download_view'),
    path('requests/', views.request_list, name='requestlistview'),
    url(r'request_details/(?P<request_id>\d+)/$', views.request_details, name='requestdetailsview'),
    path('contactus/', views.districtmanager_list, name='contactus'),
    path('reg_success/', views.RegSuccess.as_view(), name='reg_successview'),
    path('req_sucess/', views.ReqSuccess.as_view(), name='req_sucessview'),
    path('district_needs/', views.DistNeeds.as_view(), name='distneedsview'),
    path('collection_center/', views.CollectionCenterView.as_view(), name='collection_centers_view'),
    url(r'collection_centers/(?P<location>\w+)/$', views.CollectionCenterListView.as_view(), name='collection_centers_list'),
    path('collection_centers/', TemplateView.as_view(template_name='mainapp/collectioncenter_state_select.html'), name='collection_centers_district_select'),
    path('contribute/', views.contribute, name='contribute'),
    path('reg_contrib/', views.RegisterContributor.as_view(), name='reg_contribview'),
    path('contribview/', views.contributors, name='contribview'),
    path('contrib_success/', views.ContribSuccess.as_view(), name='contribsucessview'),
    path('disclaimer/', views.DisclaimerPage.as_view(), name='disclaimer'),
    path('ieee/', views.AboutIEEE.as_view(), name='aboutieee'),
    path('pcampadd' , views.RegisterPrivateReliefCamp.as_view() , name="Private Camps"),
    path('pcamp/' , views.pcamplist , name="privatecamplist"),
    path('pcampdet/' , views.pcampdetails , name="privatecampdetails"),
    path('privatecc/' , views.privatecc , name="privatedetails"),
    # path('data/' , views.data , name="data"),
    path('map/' , views.mapview , name="map"),
    path('dmodash/' , views.dmodash , name="DMODash"),
    path('dmoinfo/' , views.dmoinfo , name="DMOInfo" ),
    path('dmocsv/' , views.dmocsv , name="DMOCSV" ),
    path('dmodist/' , views.dmodist , name="DMODist" ),
    path('dmotal/' , views.dmotal , name="DMOTal" ),
    path('error/' , views.error , name="errorview" ),
    path('login/', auth_views.LoginView.as_view(template_name='mainapp/login.html'),name='user_login'),
    path('logout/', views.logout_view, name='user_logout'),
    path('relief_camps/data/', views.relief_camps_data, name='relief_camps_data'),
    path('relief_camps/', views.relief_camps, name='relief_camps'),
    path('relief_camps_list/', views.relief_camps_list, name='relief_camps_list'),
    path('camp/<int:pk>/requirements/',views.CampRequirements.as_view(),name='camp_requirements'),
    path('camp/<int:pk>/details/',views.CampDetails.as_view(),name='camp_details'),
    path('camp/<int:camp_id>/add_person/', views.AddPerson.as_view(), name='add_person'),
    path('coordinator_home/', views.coordinator_home, name='coordinator_home'),
    path('find_people/', views.find_people, name='find_people'),
    path('missing_persons/', views.missing_persons, name='missing_persons'),
    path('announcements/', views.announcements, name="Announcements"),
    path('announcements/<int:id>', views.announcements_id, name="announcements_id"),
    path('announcements/<str:filter_>', views.announcements_filter, name="announcements_filter"),
    path('camp_requirements/', views.camp_requirements_list, name='camp_requirements_list'),
    path('submission_success/', views.SubmissionSuccess.as_view(), name='submission_success'),
    url(r'request_update/(?P<request_id>\d+)/$', views.RequestUpdateView.as_view(), name='requestupdateview'),
    path('req_update_success/', views.ReqUpdateSuccess.as_view(), name='req_update_success'),
    path('consent_success/', views.ConsentSuccess.as_view(), name='consent_success'),
    url(r'c/(?P<pk>\d+)/(?P<ts>\d+)/$', views.VolunteerConsent.as_view(), name='volunteer_consent'),
    url('missing_and_finding_persons/', views.ReportFindPerson.as_view(), name='report_find_person'),
    url('hospitals/', views.HospitalView.as_view(), name='hospitals'),
    url('announcements/api', views.announcement_api, name='announcements_api'),
    url('PIF/' , views.fbannouncements , name="social_media_announcements" )
]

mainapp/models.py
import os
import uuid
from enum import Enum
import csv
import codecs
from hashlib import md5

from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save
from django.core.cache.utils import make_template_fragment_key
from django.core.cache import cache
from django.dispatch import receiver
from django.utils import timezone


districts = (
    ('alp','Alappuzha - ആലപ്പുഴ'),
    ('ekm','Ernakulam - എറണാകുളം'),
    ('idk','Idukki - ഇടുക്കി'),
    ('knr','Kannur - കണ്ണൂർ'),
    ('ksr','Kasaragod - കാസർഗോഡ്'),
    ('kol','Kollam - കൊല്ലം'),
    ('ktm','Kottayam - കോട്ടയം'),
    ('koz','Kozhikode - കോഴിക്കോട്'),
    ('mpm','Malappuram - മലപ്പുറം'),
    ('pkd','Palakkad - പാലക്കാട്'),
    ('ptm','Pathanamthitta - പത്തനംതിട്ട'),
    ('tvm','Thiruvananthapuram - തിരുവനന്തപുരം'),
    ('tcr','Thrissur - തൃശ്ശൂർ'),
    ('wnd','Wayanad - വയനാട്'),
)

status_types =(
    ('new', 'New'),
    ('pro', 'In progess'),
    ('sup', 'Supplied')
)

volunteer_update_status_types = (
    ('hig', 'High priority'),
    ('med', 'Medium priority'),
    ('low', 'Low priority'),
    ('cls', 'Can be closed'),
    ('otr', 'Other')
)

contrib_status_types =(
    ('new', 'New'),
    ('ful', 'Fullfilled'),
)

relief_camp_status = (
    ('active', 'Active'),
    ('closed', 'Closed'),
    ('duplicate', 'Duplicate')
)

vol_categories = (
    ('dcr', 'Doctor'),
    ('hsv', 'Health Services'),
    ('elw', 'Electrical Works'),
    ('mew', 'Mechanical Work'),
    ('cvw', 'Civil Work'),
    ('plw', 'Plumbing work'),
    ('vls', 'Vehicle Support'),
    ('ckg', 'Cooking'),
    ('rlo', 'Relief operation'),
    ('cln', 'Cleaning'),
    ('bot', 'Boat Service'),
    ('rck', 'Rock Climbing'),
    ('oth', 'Other')
)

gender =(
    (0,'Male'),
    (1,'Female'),
    (2,'Others')
)

announcement_types =(
    (0,'General'),
    (1,'Food'),
    (2,'Camps'),
    (3,'Weather'),
    (4, 'All'),
)

announcement_priorities = [
    ('H', 'High'),
    ('M', 'Medium'),
    ('L', 'Low')]


person_status = (
    ('new', 'New'),
    ('checked_out', 'Checked Out'),
    ('closed', 'Closed')
)

contribution_types = (
    ('fod', 'Food'),
    ('med', 'Medicines'),
    ('shl', 'Shelter'),
    ('clt', 'Clothing'),
    ('sny', 'Sanitary materials'),
    ('oth', 'Others')
)


class LSGTypes(Enum):
    CORPORATION = 0
    MUNICIPALITY = 1
    GRAMA_PANCHAYATH = 2


class Request(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
        verbose_name='District - ജില്ല'
    )
    location = models.CharField(max_length=500,verbose_name='Location - സ്ഥലം')
    requestee = models.CharField(max_length=100,verbose_name='Requestee - അപേക്ഷകന്റെ പേര്')

    phone_number_regex = RegexValidator(regex='^((\+91|91|0)[\- ]{0,1})?[456789]\d{9}$', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', code='invalid_mobile')
    requestee_phone = models.CharField(max_length=14,verbose_name='Requestee Phone - അപേക്ഷകന്റെ ഫോണ്‍ നമ്പര്‍', validators=[phone_number_regex])

    latlng = models.CharField(max_length=100, verbose_name='GPS Coordinates - GPS നിർദ്ദേശാങ്കങ്ങൾ ', blank=True)
    latlng_accuracy = models.CharField(max_length=100, verbose_name='GPS Accuracy - GPS കൃത്യത ', blank=True)
    #  If it is enabled no need to consider lat and lng
    is_request_for_others = models.BooleanField(
        verbose_name='Requesting for others - മറ്റൊരാൾക്ക് വേണ്ടി അപേക്ഷിക്കുന്നു ', default=False)

    needwater = models.BooleanField(verbose_name='Water - വെള്ളം')
    needfood = models.BooleanField(verbose_name='Food - ഭക്ഷണം')
    needcloth = models.BooleanField(verbose_name='Clothing - വസ്ത്രം')
    needmed = models.BooleanField(verbose_name='Medicine - മരുന്നുകള്‍')
    needtoilet = models.BooleanField(verbose_name='Toiletries - ശുചീകരണ സാമഗ്രികള്‍ ')
    needkit_util = models.BooleanField(verbose_name='Kitchen utensil - അടുക്കള സാമഗ്രികള്‍')
    needrescue = models.BooleanField(verbose_name='Need rescue - രക്ഷാപ്രവർത്തനം ആവശ്യമുണ്ട്')

    detailwater = models.CharField(max_length=250, verbose_name='Details for required water - ആവശ്യമായ വെള്ളത്തിന്റെ വിവരങ്ങള്‍', blank=True)
    detailfood = models.CharField(max_length=250, verbose_name='Details for required food - ആവശ്യമായ ഭക്ഷണത്തിന്റെ വിവരങ്ങള്‍', blank=True)
    detailcloth = models.CharField(max_length=250, verbose_name='Details for required clothing - ആവശ്യമായ വസ്ത്രത്തിന്റെ വിവരങ്ങള്‍', blank=True)
    detailmed = models.CharField(max_length=250, verbose_name='Details for required medicine - ആവശ്യമായ മരുന്നിന്റെ  വിവരങ്ങള്‍', blank=True)
    detailtoilet = models.CharField(max_length=250, verbose_name='Details for required toiletries - ആവശ്യമായ  ശുചീകരണ സാമഗ്രികള്‍', blank=True)
    detailkit_util = models.CharField(max_length=250, verbose_name='Details for required kitchen utensil - ആവശ്യമായ അടുക്കള സാമഗ്രികള്‍', blank=True)
    detailrescue = models.CharField(max_length=250, verbose_name='Details for rescue action - രക്ഷാപ്രവർത്തനം വിവരങ്ങള്', blank=True)

    needothers = models.CharField(max_length=500, verbose_name="Other needs - മറ്റു ആവശ്യങ്ങള്‍", blank=True)
    status = models.CharField(
        max_length = 10,
        choices = status_types,
        default = 'new'
    )
    supply_details = models.CharField(max_length=100, blank=True)
    dateadded = models.DateTimeField(auto_now_add=True)

    def summarise(self):
        out = ""
        if(self.needwater):
            out += "Water Requirements :\n {}".format(self.detailwater)
        if(self.needfood):
            out += "\nFood Requirements :\n {}".format(self.detailfood)
        if(self.needcloth):
            out += "\nCloth Requirements :\n {}".format(self.detailcloth)
        if(self.needmed):
            out += "\nMedicine Requirements :\n {}".format(self.detailmed)
        if(self.needtoilet):
            out += "\nToilet Requirements :\n {}".format(self.detailtoilet)
        if(self.needkit_util):
            out += "\nKit Requirements :\n {}".format(self.detailkit_util)
        if(self.needrescue):
            out += "\nRescue Action :\n {}".format(self.detailrescue)
        if(len(self.needothers.strip()) != 0):
            out += "\nOther Needs :\n {}".format(self.needothers)
        return out

    class Meta:
        verbose_name = 'Rescue: Request'
        verbose_name_plural = 'Rescue:Requests'

    def __str__(self):
        return '#' + str(self.id) + ' ' + self.get_district_display() + ' ' + self.location

    def is_old(self):
        return self.dateadded < (timezone.now() - timezone.timedelta(days=2))


class VolunteerGroup(models.Model):
    group_name = models.CharField(max_length = 200)

    def __str__(self):
        return "Group Name " + str(self.group_name) + " || Volunteer Count " + str(Volunteer.objects.all().filter(groups__in=[self]).count())


class Volunteer(models.Model):
    district = models.CharField(
        max_length=15,
        choices=districts,
        verbose_name="District - ജില്ല"
    )
    name = models.CharField(max_length=100, verbose_name="Name - പേര്")

    phone_number_regex = RegexValidator(regex='^((\+91|91|0)[\- ]{0,1})?[456789]\d{9}$', message='Please Enter 10 digit mobile number or landline as 0<std code><phone number>', code='invalid_mobile')
    phone = models.CharField(max_length=14, verbose_name="Phone - ഫോണ്‍ നമ്പര്‍", validators=[phone_number_regex])

    organisation = models.CharField(max_length=250, verbose_name="Organization (സംഘടന) / Institution")
    address = models.TextField(verbose_name="Address - വിലാസം")
    area = models.CharField(
        max_length = 15,
        choices = vol_categories,
        verbose_name = "Area of volunteering - സന്നദ്ധസേവനം"
    )
    is_spoc = models.BooleanField(default=False, verbose_name="Is point of contact")
    joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    has_consented = models.BooleanField(default=False, verbose_name="Available")
    groups = models.ManyToManyField(VolunteerGroup)

    class Meta:
        verbose_name = 'Volunteer: Individual'
        verbose_name_plural = 'Volunteers: Individuals'

    def __str__(self):
        return self.name


class NGO(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
    )
    organisation = models.CharField(max_length=250, verbose_name="Name of Organization (സംഘടനയുടെ പേര്)")
    organisation_type = models.CharField(max_length=250, verbose_name="Type of Organization")
    organisation_address = models.TextField(default='', verbose_name="Address of Organization")
    name = models.CharField(max_length=100, verbose_name="Contact Person")
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    description = models.TextField(verbose_name="About Organisation")
    area = models.TextField(
        verbose_name = "Area of volunteering"
    )
    location = models.CharField(
        max_length=500,
        verbose_name="Preferred Location to Volunteer"
    )
    website_url = models.CharField(max_length=300,verbose_name="Enter your website link",default='')
    is_spoc = models.BooleanField(default=False, verbose_name="Is point of contact")
    joined = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Volunteer: NGO'
        verbose_name_plural = 'Volunteers: NGOs'

    def __str__(self):
        return self.name


class Contributor(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
        verbose_name="District - ജില്ല"
    )

mainapp/templates/mainapp/aboutieee.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<div class="row text-center static-page-box">
    <h1 class="text-center">About IEEE</h1>
    <p style="font-size:1.7rem;">IEEE– Institute of Electrical and Electronics Engineers, is the world’s largest technical professional society, is continuously promoting the development and application of technology and allied sciences for the benefit of humanity and for the advancement of the profession. Formally started in 1963, IEEE now has 430,000 members spanning across 165 countries of the globe. IEEE fosters the development of standards and advancement of technology for the benifit of humanity.</p>
    <p style="font-size:1.7rem;">
        IEEE Kerala Section, one of the 11 Sections of IEEE in India was founded by the technology giant of Kerala, Late KPP Nambiar in 1983. Several innovations from IEEE Kerala Section in organizing activities for students as well as professionals have been appreciated and replicated by the global IEEE community. Winner of MGA Large Section Award in 2015 and Region 10 (Asia Pacific) Outstanding Large Section Award in 2004, 2009 and 2015, IEEE Kerala Section has been organizing high quality, high impact technical events and humanitarian projects. Please visit our website https://ieeekerala.org/ for more details about the activities of IEEE Kerala section.</p>
</div>
{% endblock %}

mainapp/templates/mainapp/contrib_success.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<!--Navigation Breadcrumbs-->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Contributor Registered</li>
  </ol>
</nav>

<h3 align="center">Our volunteer will contact you soon for collection</h3>
<h3 align="center">ഞങ്ങളുടെ വോളന്റീയർ താങ്കളുമായി ബന്ധപ്പെടുന്നതായിരിക്കും</h3>

{% endblock %}

mainapp/templates/mainapp/contributor_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<!--Navigation Breadcrumbs-->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Contributor Form</li>
  </ol>
</nav>

<h1 class="text-center">To Contribute Materials/Services</h1>
<h2 class="text-center">സംഭാവന നല്‍കാന്‍ ഉദ്ദേശിക്കുന്ന സാധനങ്ങള്‍/സേവനം</h2>
  <form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">
  {% bootstrap_icon "star" %} Submit
  </button>
  {% endbuttons %}
  </form>
<script>
    window.addEventListener('load', function() {
        $("#id_phone").attr('type', 'number');
    });
</script>
{% endblock %}

mainapp/templates/mainapp/disclaimer.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<div class="row text-center static-page-box">
    <h1 class="text-center">Disclaimer</h1>
    <p style="font-size:1.7rem;">This portal has been developed for effective collaboration between various stakeholders such as citizen, Government authorities, various NGOs and volunteers. IEEE makes no representation regarding the completeness, accuracy of any information and data contained on this portal or that such information and data will be error-free. Stakeholders are trying to make their best effort to support, any information received through the portal the requests received through this portal doesn’t warrant any commitment on the services. By using this site you acknowledge that you have read and agree to this</p>
    <br>
    <h1 class="text-center">GDPR Compliance</h1>
    <p style="font-size:1.7rem;">By providing your personal information, you consent to making such information accessible to persons who visit this website. You further acknowledge and agree that in order to serve the specific purposes for which personal information is volunteered by you, such information needs to be accessible to the public at large and therefore, by volunteering your information on this website, you consent to making such information public. By providing your phone number and email address, you further consent to being contacted by anyone who accesses such information through this website. The creators of this website or the government of Kerala shall not be liable for any unauthorized use, misuse or sharing of such information.</p>
</div>
{% endblock %}

mainapp/templates/mainapp/districtmanager_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<!--Navigation Breadcrumbs-->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Contact Info</li>
  </ol>
</nav>

<h1 class="text-center">Contact Info</h1>
<h2 class="text-center">ഞങ്ങളുമായി ബന്ധപ്പെടാന്‍</h2>
<p class="text-center">
  Volunteers are available across Kerala. Contact the <u>District level point of contacts</u> for any help. <br/>
  സഹായത്തിനായി വൊളന്‍റീയര്‍മാര്‍ തയ്യാറാണ്. സഹായം ആവശ്യമെങ്കില്‍ ഒരോ ജില്ലയിലെയും നിയോഗിക്കപെട്ട ഉദ്യോഗസ്ഥരുമായി ബന്ധപ്പെടാം
</p>
<form id="find-contact-form" action="" method="get">
       {% bootstrap_form filter.form bound_css_class=False %}
 </form>
 <div class="table-responsive">
  <table class="table">
    <tr>
      <th>Name - പേര്</th>
      <th>Phone - ഫോൺ</th>
      <th>Other Contact - മറ്റ് കോൺടാക്റ്റ്</th>
    </tr>
    {% for req in filter.qs %}
        <tr>
          <td>{{ req.name }}</td>
          <td><a href="tel:{{ req.phone }}">{{ req.phone }}</a></td>          <td>{{ req.email }}</td>
        </tr>
    {% endfor %}
  </table>
</div>
<script>
  window.addEventListener('load', function() {
    $("#id_district").change(() => {
      $("#find-contact-form").submit();
    })
    $('#id_district').selectize();
  });

</script>
{% endblock %}

mainapp/templates/mainapp/ngo_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<!--Navigation Breadcrumbs-->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="{%url 'ngovolunteerview' %}">Register as a Volunteer or NGO</a></li>
    <li class="breadcrumb-item active" aria-current="page">NGO-Company Registration</li>
  </ol>
</nav>

  <div class="text-right">
    <a href="{% url 'ngo_download_view' %}">Download NGO list</a>
  </div>

<p class="text-center">
  <h1 class="text-center">NGO/Company Registration</h1>
  <h2 class="text-center"></h2>
</p>
  <form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">
  {% bootstrap_icon "star" %} Submit
  </button>
  {% endbuttons %}
  </form>

<script type="text/javascript">
  window.addEventListener('load', function() {
    $(function() {
      $('#id_district').selectize();
    });
  });
</script>
{% endblock %}

mainapp/templates/mainapp/privaterescuecamp_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block content %}

<!--Navigation Breadcrumbs-->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="{%url 'privatedetails' %}">Private Relief & Collection Centres</a></li>
    <li class="breadcrumb-item active" aria-current="page">Add Private Relief Camp</li>
  </ol>
</nav>

<h1 class="text-center">Enter New Camp Details</h1>
<h2 class="text-center">പുതിയ ക്യാമ്പിന്റെ വിശദാംശങ്ങൾ  നൽകുക </h2>
  <form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">
  {% bootstrap_icon "star" %} Submit
  </button>
  {% endbuttons %}
  </form>


    {% block javascript %}

        <script type="text/javascript" src="{% static 'js/form-lsg-ward-picker.js' %}"></script>
    {% endblock %}

{% endblock %}

mainapp/templates/mainapp/reliefcampdata_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<h1 class="text-center">Add Relief Camp Data</h1>
<h2 class="text-center">ക്യാമ്പുകളെ കുറിച്ചുള്ള വിവരങ്ങൾ ചേർക്കുക‍</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
    {% bootstrap_icon "star" %} Submit
    </button>
    {% endbuttons %}
  </form>

<script>
    window.addEventListener('load', function() {
        $("#id_phone").attr('type', 'number');
    });
</script>
{% endblock %}

mainapp/templates/mainapp/req_success.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<h3 align="center">Request successfully registered</h3>
<h3 align="center">താങ്കളുടെ അപേക്ഷ രജിസ്റ്റർ ചെയ്തിരിക്കുന്നു</h3>

{% endblock %}

mainapp/templates/mainapp/submission_success.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<h3 align="center">Data successfully registered</h3>
<h3 align="center">വിവരങ്ങൾ വിജയകരമായി രജിസ്റ്റർ ചെയ്തിരിക്കുന്നു</h3>

{% endblock %}

mainapp/templates/mainapp/volunteer_consent_success.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<h3 align="center">Thank you for your efforts, we'll contact you soon</h3>
<h3 align="center">താങ്കളുടെ പ്രയത്നങ്ങൾക്കു നന്ദി, താങ്കളുമായി ഉടൻ ബന്ധപെടുന്നതായിരിക്കും</h3>

{% endblock %}